title: Risan's Programming Blog
heading: Risan
description: Risan Bagja on software development and coding practice.
author: Risan Bagja Pradana

# Serving.
port: 4001
host: localhost
url: http://localhost:4001
css_dir: assets/css
img_dir: assets/img
js_dir: assets/js

# Configuration.
lang: en
encoding: utf-8
timezone: Europe/Stockholm
markdown: kramdown
highlighter: pygments
permalink: /:title.html
paginate: 2
paginate_path: /page/:num
liquid:
  error_mode: strict

# Front matter defaults.
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Plugins.
gems:
  - jekyll-feed
  - jekyll-paginate
  - octopress-minify-html
  - pygments.rb

# Minify HTML.
minify_html: false
html_press:
  unquoted_attributes: false
  drop_empty_values: true
  strip_crlf: true
  js_minifier_options: false

# Directories.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - gulp-tasks
  - node_modules
  - package.json
  - yarn.lock
keep_files:
  - .git
  - assets
